# Generated by Django 4.0.4 on 2022-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
